AWSTemplateFormatVersion: 2010-09-09
Description: An example CloudFormation template for Fargate.
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0a54f5ed456524114
  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0f15e0746544ff8d6
  SubnetB:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0e55aa84d73921b28
  Certificate:
    Type: String
    # Update with the certificate ARN from Certificate Manager, which must exist in the same region.
    Default: 'arn:aws:acm:us-east-1:527047085842:certificate/3f20d90c-b73b-4fa6-a076-f08718068d2f'
  ImageEmployee:
    Type: String
    # Update with the Docker image. "You can use images in the Docker Hub registry or specify other repositories (repository-url/image:tag)."
    Default: 527047085842.dkr.ecr.us-east-1.amazonaws.com/employee:v2
  
  ImageAttendance:
    Type: String
    # Update with the Docker image. "You can use images in the Docker Hub registry or specify other repositories (repository-url/image:tag)."
    Default: 527047085842.dkr.ecr.us-east-1.amazonaws.com/attendance:v1

  ServiceName:
    Type: String
    # update with the name of the service
    Default: MyService
  ContainerPortEmployee:
    Type: Number
    Default: 3000
  ContainerPortAttendance:
    Type: Number
    Default: 3001
  LoadBalancerPort:
    Type: Number
    Default: 443
  HealthCheckPath:
    Type: String
    Default: /
  HostedZoneName:
    Type: String
    Default: bunthoeurn.train.mbanq.cloud
  Subdomain:
    Type: String
    Default: api
  # for autoscaling
  MinContainers:
    Type: Number
    Default: 2
  # for autoscaling
  MaxContainers:
    Type: Number
    Default: 2
  # target CPU utilization (%)
  AutoScalingTargetValue:
    Type: Number
    Default: 50
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]

  TaskDefinitionEmployee:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Name of the task definition. Subsequent versions of the task definition are grouped together under this name.
      Family: !Sub ${ServiceName}-employee
      # awsvpc is required for Fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
      # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
      # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
      # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
      # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
      Cpu: 256
      # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
      # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
      # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
      # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
      # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
      Memory: 0.5GB
      # A role needed by ECS.
      # "The ARN of the task execution role that containers in this task can assume. All containers in this task are granted the permissions that are specified in this role."
      # "There is an optional task execution IAM role that you can specify with Fargate to allow your Fargate tasks to make API calls to Amazon ECR."
      ExecutionRoleArn: !Ref ExecutionRole
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that grants containers in the task permission to call AWS APIs on your behalf."
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Sub ${ServiceName}-container-employee
          Image: !Ref ImageEmployee
          PortMappings:
            - ContainerPort: !Ref ContainerPortEmployee

  TaskDefinitionAttendance:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Name of the task definition. Subsequent versions of the task definition are grouped together under this name.
      Family: !Sub ${ServiceName}-attendance
      # awsvpc is required for Fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
      # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
      # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
      # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
      # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
      Cpu: 256
      # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
      # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
      # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
      # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
      # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
      Memory: 0.5GB
      # A role needed by ECS.
      # "The ARN of the task execution role that containers in this task can assume. All containers in this task are granted the permissions that are specified in this role."
      # "There is an optional task execution IAM role that you can specify with Fargate to allow your Fargate tasks to make API calls to Amazon ECR."
      ExecutionRoleArn: !Ref ExecutionRole
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that grants containers in the task permission to call AWS APIs on your behalf."
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Sub ${ServiceName}-container-attendance
          Image: !Ref ImageAttendance
          PortMappings:
            - ContainerPort: !Ref ContainerPortAttendance
        

  # A role needed by ECS
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  # A role for the containers
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, TaskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      # ManagedPolicyArns:
      #   -
      # Policies:
      #   -

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref ServiceName, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPortEmployee
          ToPort: !Ref ContainerPortEmployee
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref ContainerPortAttendance
          ToPort: !Ref ContainerPortAttendance
          CidrIp: 0.0.0.0/0

  ServiceEmployee:
    Type: AWS::ECS::Service
    # This dependency is needed so that the load balancer is setup correctly in time
    DependsOn:
      - ListenerHTTPSEmployee
    Properties: 
      ServiceName: !Sub ${ServiceName}-service-employee
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionEmployee
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      # This may need to be adjusted if the container takes a while to start up
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Sub ${ServiceName}-container-employee
          ContainerPort: !Ref ContainerPortEmployee
          TargetGroupArn: !Ref TargetGroupEmployee
  
  ServiceAttendance:
    Type: AWS::ECS::Service
    # This dependency is needed so that the load balancer is setup correctly in time
    DependsOn:
      - ListenerHTTPSAttendance
    Properties: 
      ServiceName: !Sub ${ServiceName}-service-attendance
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionAttendance
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      # This may need to be adjusted if the container takes a while to start up
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Sub ${ServiceName}-container-attendance
          ContainerPort: !Ref ContainerPortAttendance
          TargetGroupArn: !Ref TargetGroupAttendance

  TargetGroupEmployee:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Join ['', [!Ref ServiceName, TargetGroupEmployeee]]
      Port: !Ref ContainerPortEmployee
      Protocol: TCP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      TargetType: ip
      VpcId: !Ref VPC
  
  TargetGroupAttendance:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Join ['', [!Ref ServiceName, TargetGroupAttendancee]]
      Port: !Ref ContainerPortAttendance
      Protocol: TCP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      TargetType: ip
      VpcId: !Ref VPC

  ListenerHTTPSEmployee:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroupEmployee
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerEmployee
      Port: !Ref LoadBalancerPort
      Protocol: TLS
      Certificates:
        - CertificateArn: !Ref Certificate

  ListenerHTTPSAttendance:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroupAttendance
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerAttendance
      Port: !Ref LoadBalancerPort
      Protocol: TLS
      Certificates:
        - CertificateArn: !Ref Certificate

  LoadBalancerEmployee:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ['', [!Ref ServiceName, LoadBalancerEmployeee]]
      # "internal" is also an option
      Scheme: internal
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
      Type: network

  LoadBalancerAttendance:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ['', [!Ref ServiceName, LoadBalancerAttendancee]]
      # "internal" is also an option
      Scheme: internal
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
      Type: network
  
  ApiGatewayVPCLinkEmployee:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Description: ApiGateway Link to Core Network LoadBalancer in VPC
      Name: ApiGatewayVPCLinkEmployee
      TargetArns:
        - !Ref LoadBalancerEmployee
  
  ApiGatewayVPCLinkAttendance:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Description: ApiGateway Link to Core Network LoadBalancer in VPC
      Name: ApiGatewayVPCLinkAttendance
      TargetArns:
        - !Ref LoadBalancerAttendance
  
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - EDGE
      Name: Api
  
  RestApiResourceEmployee:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: employee
      RestApiId: !Ref RestApi

  RestApiResourceAttendance:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: attendance
      RestApiId: !Ref RestApi
  
  RestApiMethodEmployee:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVPCLinkEmployee
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: "https://api.bunthoeurn.train.mbanq.cloud"
      ResourceId: !GetAtt RestApiResourceEmployee.ResourceId
      RestApiId: !Ref RestApi

  RestApiMethodAttendance:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVPCLinkAttendance
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: "https://api.bunthoeurn.train.mbanq.cloud"
      ResourceId: !GetAtt RestApiResourceAttendance.ResourceId
      RestApiId: !Ref RestApi
  
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref Certificate
      DomainName: !Sub ${Subdomain}.${HostedZoneName}
      EndpointConfiguration:
        Types:
          - EDGE
      SecurityPolicy: TLS_1_2
  
  ApiRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref HostedZoneName, .]]
      Name: !Ref ApiDomainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt ApiDomainName.DistributionHostedZoneId
        DNSName: !GetAtt ApiDomainName.DistributionDomainName
  
  RestApiDeployment:
      Type: AWS::ApiGateway::Deployment
      DependsOn:
        - RestApiMethodAttendance
        - RestApiMethodEmployee
      Properties:
        RestApiId: !Ref RestApi

  RestApiStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId: !Ref RestApiDeployment
        RestApiId: !Ref RestApi
        StageName: "stage"
  
  ApiDomainPathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref RestApi
      Stage: !Ref RestApiStage